# Phase 4: observability and scale.
#
# Three concerns, deliberately separated:
#   - alarms      
#   - autoscaling
#   - dashboard   
# 
# notification target
# 

resource "aws_sns_topic" "alerts" {
  name = "${local.name}-alerts"
}

# Email subscriptions require the recipient to click a confirmation link.
# If not done so, the subscription is "pending confirmation" and alarms fire
# into the void.
resource "aws_sns_topic_subscription" "alerts_email" {
  count = var.alert_email == "" ? 0 : 1

  topic_arn = aws_sns_topic.alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}

locals {
  alarm_targets = [aws_sns_topic.alerts.arn]
}

# 
# alarms: the load balancer
#
# Measure what a user experiences. ECS and RDS metrics explain *why* something is slow; ALB
# metrics tell that it is. 
# 

resource "aws_cloudwatch_metric_alarm" "alb_target_5xx" {
  alarm_name        = "${local.name}-target-5xx"
  alarm_description = "The application returned 5xx responses. Check the ECS task logs."

  namespace   = "AWS/ApplicationELB"
  metric_name = "HTTPCode_Target_5XX_Count"
  statistic   = "Sum"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.app.arn_suffix
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alarm_5xx_threshold
  period              = 60
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

# 5xx generated by the load balancer itself. Usually means no
# healthy targets, or targets refusing connections. Different cause, so a
# different alarm.
resource "aws_cloudwatch_metric_alarm" "alb_elb_5xx" {
  alarm_name        = "${local.name}-elb-5xx"
  alarm_description = "The load balancer could not reach a healthy target."

  namespace   = "AWS/ApplicationELB"
  metric_name = "HTTPCode_ELB_5XX_Count"
  statistic   = "Sum"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = 0
  period              = 60
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

# p95, not Average. An average hides the tail, and the tail is where the
# users live: the 4m47s write in the phase 4 load test barely moved the mean.
resource "aws_cloudwatch_metric_alarm" "alb_latency" {
  alarm_name        = "${local.name}-latency-p95"
  alarm_description = "p95 response time exceeded the service objective."

  namespace          = "AWS/ApplicationELB"
  metric_name        = "TargetResponseTime"
  extended_statistic = "p95"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.app.arn_suffix
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alarm_latency_p95_seconds
  period              = 60
  evaluation_periods  = 3
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

resource "aws_cloudwatch_metric_alarm" "unhealthy_targets" {
  alarm_name        = "${local.name}-unhealthy-targets"
  alarm_description = "At least one task is failing the /healthz check."

  namespace   = "AWS/ApplicationELB"
  metric_name = "UnHealthyHostCount"
  statistic   = "Maximum"

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.app.arn_suffix
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = 0
  period              = 60
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

# 
# alarms: the database
#
# db.t4g.micro has 1 GiB of memory, and RDS derives max_connections from
# memory: roughly 112 for this class. The pool in db.py opens up to
# `desired_count * pool_max` connections, so this ceiling is reachable.
# 

resource "aws_cloudwatch_metric_alarm" "rds_connections" {
  alarm_name        = "${local.name}-rds-connections"
  alarm_description = "Database connections approaching the instance limit (~112 on db.t4g.micro)."

  namespace   = "AWS/RDS"
  metric_name = "DatabaseConnections"
  statistic   = "Maximum"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alarm_db_connections_threshold
  period              = 60
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

resource "aws_cloudwatch_metric_alarm" "rds_cpu" {
  alarm_name        = "${local.name}-rds-cpu"
  alarm_description = "Database CPU sustained high. Look for missing indexes before resizing."

  namespace   = "AWS/RDS"
  metric_name = "CPUUtilization"
  statistic   = "Average"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }

  comparison_operator = "GreaterThanThreshold"
  threshold           = 80
  period              = 300
  evaluation_periods  = 2
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
  ok_actions    = local.alarm_targets
}

resource "aws_cloudwatch_metric_alarm" "rds_cpu_credits" {
  alarm_name        = "${local.name}-rds-cpu-credits"
  alarm_description = "Burst credit balance low. Sustained load will be throttled to baseline."

  namespace   = "AWS/RDS"
  metric_name = "CPUCreditBalance"
  statistic   = "Minimum"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }

  comparison_operator = "LessThanThreshold"
  threshold           = 20
  period              = 300
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
}

resource "aws_cloudwatch_metric_alarm" "rds_storage" {
  alarm_name        = "${local.name}-rds-free-storage"
  alarm_description = "Free storage below 2 GiB."

  namespace   = "AWS/RDS"
  metric_name = "FreeStorageSpace"
  statistic   = "Minimum"

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.main.identifier
  }

  comparison_operator = "LessThanThreshold"
  threshold           = 2 * 1024 * 1024 * 1024
  period              = 300
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets
}

# 
# alarms: application logs
#
# A metric filter turns log lines into a CloudWatch metric. Here, the pool exhaustion that
# showed up as `db_connection_errors` in the k6 run.
# 

resource "aws_cloudwatch_log_metric_filter" "app_errors" {
  name           = "${local.name}-app-errors"
  log_group_name = aws_cloudwatch_log_group.app.name

  # Matches ERROR / CRITICAL / Traceback anywhere in the line.
  pattern = "?ERROR ?CRITICAL ?Traceback"

  metric_transformation {
    name          = "AppErrorCount"
    namespace     = "Booklog/${var.environment}"
    value         = "1"
    default_value = "0"
    unit          = "Count"
  }
}

resource "aws_cloudwatch_metric_alarm" "app_errors" {
  alarm_name        = "${local.name}-app-errors"
  alarm_description = "Application logged errors or tracebacks."

  namespace   = "Booklog/${var.environment}"
  metric_name = "AppErrorCount"
  statistic   = "Sum"

  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alarm_app_error_threshold
  period              = 300
  evaluation_periods  = 1
  treat_missing_data  = "notBreaching"

  alarm_actions = local.alarm_targets

  depends_on = [aws_cloudwatch_log_metric_filter.app_errors]
}

# 
# autoscaling
#
# Target tracking, not step scaling. 
#
# 

resource "aws_appautoscaling_target" "ecs" {
  service_namespace  = "ecs"
  resource_id        = "service/${aws_ecs_cluster.main.name}/${aws_ecs_service.app.name}"
  scalable_dimension = "ecs:service:DesiredCount"

  min_capacity = var.autoscaling_min_capacity
  max_capacity = var.autoscaling_max_capacity
}

resource "aws_appautoscaling_policy" "ecs_cpu" {
  name               = "${local.name}-cpu-target"
  policy_type        = "TargetTrackingScaling"
  service_namespace  = aws_appautoscaling_target.ecs.service_namespace
  resource_id        = aws_appautoscaling_target.ecs.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs.scalable_dimension

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }

    target_value = var.autoscaling_cpu_target

    # Scale out fast, scale in slow. A premature scale-in during a traffic
    # trough costs a cold start when it returns; the asymmetry is
    # intentional.
    scale_out_cooldown = 60
    scale_in_cooldown  = 300
  }
}

# A second policy on request count. CPU alone misses the case where tasks are
# blocked on the database - low CPU, long queues, and no scale-out. Whichever
# policy asks for more capacity wins.
resource "aws_appautoscaling_policy" "ecs_requests" {
  name               = "${local.name}-requests-target"
  policy_type        = "TargetTrackingScaling"
  service_namespace  = aws_appautoscaling_target.ecs.service_namespace
  resource_id        = aws_appautoscaling_target.ecs.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs.scalable_dimension

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ALBRequestCountPerTarget"
      resource_label         = "${aws_lb.main.arn_suffix}/${aws_lb_target_group.app.arn_suffix}"
    }

    target_value = var.autoscaling_requests_per_target

    scale_out_cooldown = 60
    scale_in_cooldown  = 300
  }
}

# 
# dashboard
# 

resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = local.name

  dashboard_body = jsonencode({
    widgets = [
      {
        type = "text", x = 0, y = 0, width = 24, height = 1
        properties = {
          markdown = "## ${local.name} — read top to bottom: user experience, then capacity, then database"
        }
      },

      # row 1: what the user experiences 
      {
        type = "metric", x = 0, y = 1, width = 12, height = 6
        properties = {
          title  = "Response time (p50 / p95 / p99)"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          yAxis  = { left = { label = "seconds", showUnits = false, min = 0 } }
          metrics = [
            [
              "AWS/ApplicationELB", "TargetResponseTime",
              "LoadBalancer", aws_lb.main.arn_suffix,
              "TargetGroup", aws_lb_target_group.app.arn_suffix,
              { stat = "p50", label = "p50" }
            ],
            ["...", { stat = "p95", label = "p95" }],
            ["...", { stat = "p99", label = "p99" }]
          ]
          annotations = {
            horizontal = [{
              label = "p95 objective"
              value = var.alarm_latency_p95_seconds
            }]
          }
        }
      },
      {
        type = "metric", x = 12, y = 1, width = 12, height = 6
        properties = {
          title  = "Requests and errors"
          region = var.region
          view   = "timeSeries"
          stat   = "Sum"
          period = 60
          metrics = [
            [
              "AWS/ApplicationELB", "RequestCount",
              "LoadBalancer", aws_lb.main.arn_suffix,
              "TargetGroup", aws_lb_target_group.app.arn_suffix,
              { label = "requests" }
            ],
            [".", "HTTPCode_Target_2XX_Count", ".", ".", ".", ".", { label = "2xx" }],
            [".", "HTTPCode_Target_4XX_Count", ".", ".", ".", ".", { label = "4xx" }],
            [".", "HTTPCode_Target_5XX_Count", ".", ".", ".", ".", { label = "5xx" }]
          ]
        }
      },

      # row 2: capacity 
      {
        type = "metric", x = 0, y = 7, width = 8, height = 6
        properties = {
          title  = "ECS utilization"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          yAxis  = { left = { label = "percent", showUnits = false, min = 0, max = 100 } }
          metrics = [
            [
              "AWS/ECS", "CPUUtilization",
              "ClusterName", aws_ecs_cluster.main.name,
              "ServiceName", aws_ecs_service.app.name,
              { label = "CPU" }
            ],
            [".", "MemoryUtilization", ".", ".", ".", ".", { label = "memory" }]
          ]
          annotations = {
            horizontal = [{
              label = "autoscaling target"
              value = var.autoscaling_cpu_target
            }]
          }
        }
      },
      {
        type = "metric", x = 8, y = 7, width = 8, height = 6
        properties = {
          title  = "Running tasks (autoscaling in action)"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          yAxis  = { left = { label = "tasks", showUnits = false, min = 0 } }
          metrics = [
            [
              "ECS/ContainerInsights", "RunningTaskCount",
              "ClusterName", aws_ecs_cluster.main.name,
              "ServiceName", aws_ecs_service.app.name,
              { label = "running" }
            ],
            [".", "DesiredTaskCount", ".", ".", ".", ".", { label = "desired" }]
          ]
        }
      },
      {
        type = "metric", x = 16, y = 7, width = 8, height = 6
        properties = {
          title  = "Target health"
          region = var.region
          view   = "timeSeries"
          stat   = "Maximum"
          period = 60
          metrics = [
            [
              "AWS/ApplicationELB", "HealthyHostCount",
              "LoadBalancer", aws_lb.main.arn_suffix,
              "TargetGroup", aws_lb_target_group.app.arn_suffix,
              { label = "healthy" }
            ],
            [".", "UnHealthyHostCount", ".", ".", ".", ".", { label = "unhealthy" }]
          ]
        }
      },

      #row 3: the database 
      {
        type = "metric", x = 0, y = 13, width = 8, height = 6
        properties = {
          title  = "RDS connections"
          region = var.region
          view   = "timeSeries"
          stat   = "Maximum"
          period = 60
          yAxis  = { left = { label = "connections", showUnits = false, min = 0 } }
          metrics = [
            [
              "AWS/RDS", "DatabaseConnections",
              "DBInstanceIdentifier", aws_db_instance.main.identifier
            ]
          ]
          annotations = {
            horizontal = [{
              label = "alarm threshold"
              value = var.alarm_db_connections_threshold
            }]
          }
        }
      },
      {
        type = "metric", x = 8, y = 13, width = 8, height = 6
        properties = {
          title  = "RDS CPU and burst credits"
          region = var.region
          view   = "timeSeries"
          period = 60
          metrics = [
            [
              "AWS/RDS", "CPUUtilization",
              "DBInstanceIdentifier", aws_db_instance.main.identifier,
              { stat = "Average", label = "CPU %", yAxis = "left" }
            ],
            [".", "CPUCreditBalance", ".", ".", { stat = "Minimum", label = "credits", yAxis = "right" }]
          ]
          yAxis = {
            left  = { label = "percent", showUnits = false, min = 0, max = 100 }
            right = { label = "credits", showUnits = false, min = 0 }
          }
        }
      },
      {
        type = "metric", x = 16, y = 13, width = 8, height = 6
        properties = {
          title  = "RDS latency"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          yAxis  = { left = { label = "seconds", showUnits = false, min = 0 } }
          metrics = [
            [
              "AWS/RDS", "ReadLatency",
              "DBInstanceIdentifier", aws_db_instance.main.identifier,
              { label = "read" }
            ],
            [".", "WriteLatency", ".", ".", { label = "write" }]
          ]
        }
      },

      #row 4: errors in the logs 
      {
        type = "log", x = 0, y = 19, width = 24, height = 6
        properties = {
          title  = "Recent application errors"
          region = var.region
          view   = "table"
          query  = <<-EOT
            SOURCE '${aws_cloudwatch_log_group.app.name}'
            | fields @timestamp, @message
            | filter @message like /(?i)(error|critical|traceback|timeout)/
            | sort @timestamp desc
            | limit 50
          EOT
        }
      }
    ]
  })
}
